image: python:3.7
pages:
    script:
    - pip install sphinx
    - pip install -r requirements.txt
    - pip install sphinx_rtd_theme
    - pip install recommonmark
    - make docs
    - mv docs/_build/html public
    artifacts:
        paths:
            - public

    only:
    - master
