image: python:3.7
pages:
    script:
    - pip install sphinx
    - pip install sphinx_rtd_theme
    - pip install recommonmark
    - sphinx-build -d docs/_build/doctrees docs docs/_build/html
    - mv docs/_build/html public
    artifacts:
        paths:
            - public

    only:
    - master
